### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sjentzsch** [lepe/scripts#2]
Hi Lepe,
would you mind attach a license to your scripts?
I would love to use your script "compare_ubuntu_apt.pl" within a commercial setup, but only with permission to do so.
Best
Sören

**Comment by lepe** [comment]
Sure, I will do that as soon as I can have some time. Please feel free to
use the scripts in your applications. If you find any bug please let me
know.

Have a nice day!

**Comment by lepe** [comment]
Added License

**Comment by sjentzsch** [comment]
Thanks lepe!
Keep up your good work, and have a nice day too :)
